### ISSUE TITLE
No indication when you get a new craving

### ISSUE THREAD

**Issue by jesmores** [Darkhax-Minecraft/Cravings#3]
Not sure if this is intentional, but I only get chat messages when I fail to fulfill a craving, not when I get a new one. There is the `/cravings info` command, but I'd rather not have to check that every few minutes. Great mod for encouraging food exploration though, especially paired with something like Nutrition. I prefer this method over Spice of Life. Thanks!

Cravings 1.12.2-1.0.2
Forge 14.23.0.2548
Minecraft 1.12.2

**Comment by Darkhax** [comment]
Thanks for the report. There actually is a message in the code, but it seems it's not getting sent. I will try to have a quick fix out soon!

**Comment by Darkhax** [comment]
This issue was hopefully fixed with https://github.com/Darkhax-Minecraft/Cravings/commit/35d28d6b51e84ac48185742a055e9056c5bee8ca. The new version is currently pending on curse for approval, when it's accepted you can download it [here](https://minecraft.curseforge.com/projects/cravings/files/2501928).

**Comment by jesmores** [comment]
Thanks! I'll check it and report back when I get home today.

**Comment by jesmores** [comment]
Works for me now, thanks! My first craving was a Potato, haha ...
